version: '3.3'

services:
  crackhash-manager:
    build: ./manager
    networks:
      - crackhash
    env_file:
      - .env
    ports:
      - "10010:80"
  crackhash-worker-one:
    build: ./worker
    networks:
      - crackhash
    env_file:
      - .env
  crackhash-worker-two:
    build: ./worker
    networks:
      - crackhash
    env_file:
      - .env

networks:
  crackhash:
    driver: bridge

