version: '3.3'

services:
  crackhash-manager:
    env_file:
      - .env
    build: ./manager/
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - crackhash
    ports:
      - '10010:80'
    restart: on-failure

  crackhash-worker-1:
    environment:
      WORKER_NUMBER: 1
    env_file:
      - .env
    build: ./worker/
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - crackhash
    restart: on-failure

  crackhash-worker-2:
    environment:
      WORKER_NUMBER: 2
    env_file:
      - .env
    build: ./worker/
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - crackhash
    restart: on-failure

  rabbitmq:
    image: 'rabbitmq:3.13.0-management-alpine'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBIT_VHOST}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - crackhash
    restart: on-failure
    ports:
      - '5672:5672'
      - '15672:15672'

networks:
  crackhash:
    driver: bridge

