version: '3.3'

services:
  crackhash-manager:
    build: ./manager/
    networks:
      - crackhash
    env_file:
      - .env
    ports:
      - "10010:80"
    restart: on-failure
  crackhash-worker-1:
    build: ./worker/
    networks:
      - crackhash
    env_file:
      - .env
    #    deploy:
    #      mode: replicated
    #      replicas: 4
    #      endpoint_mode: dnsrr
    restart: on-failure
  crackhash-worker-2:
    build: ./worker/
    networks:
      - crackhash
    env_file:
      - .env
    #    deploy:
    #      mode: replicated
    #      replicas: 4
    #      endpoint_mode: dnsrr
    restart: on-failure
  crackhash-worker-3:
    build: ./worker/
    networks:
      - crackhash
    env_file:
      - .env
    #    deploy:
    #      mode: replicated
    #      replicas: 4
    #      endpoint_mode: dnsrr
    restart: on-failure
  crackhash-worker-4:
    build: ./worker/
    networks:
      - crackhash
    env_file:
      - .env
    #    deploy:
    #      mode: replicated
    #      replicas: 4
    #      endpoint_mode: dnsrr
    restart: on-failure

networks:
  crackhash:
    driver: bridge

