version: '3.3'

services:
  crackhash-manager:
    build: ./manager/
    networks:
      - crackhash
    env_file:
      - .env
    ports:
      - "10010:80"
    restart: always
  crackhash-worker:
    build: ./worker/
    networks:
      - crackhash
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 4
    restart: always

networks:
  crackhash:
    driver: bridge

