version: '3.3'

services:
  crackhash-manager:
    env_file:
      - .env
    image: fa251e9d106f0d5a9710eb9a3e0f65f1081086560667ef349e17eb96a2cd4332
    networks:
      - crackhash
    ports:
      - '10010:80'
    restart: on-failure

  crackhash-worker-1:
    env_file:
      - .env
    image: 6697501d8eeac1c34353af4eac36385465eb7fc964929bbcaa84199a7c4a7b44
    networks:
      - crackhash
    restart: on-failure

  rabbitmq:
    image: 'rabbitmq:3.13.0-management-alpine'
    environment:
      RABBITMQ_DEFAULT_USER: notification
      RABBITMQ_DEFAULT_PASS: notification
    networks:
      - crackhash
    ports:
      - '5672:5672'
      - '15672:15672'

networks:
  crackhash:
    driver: bridge

