version: '3.3'

services:
  crackhash-manager:
    env_file:
      - .env
    image: 1c3bb3a3421d67ad018c15bb4ed1a9c2b4edd76ae081883dfb6a69b13163ace3
    networks:
      - crackhash
    ports:
      - "10010:80"
    restart: on-failure
  crackhash-worker-1:
    env_file:
      - .env
    build: ./worker/
    networks:
      - crackhash
    #    deploy:
    #      mode: replicated
    #      replicas: 4
    #      endpoint_mode: dnsrr
    restart: on-failure
  crackhash-worker-2:
    env_file:
      - .env
    build: ./worker/
    networks:
      - crackhash
    restart: on-failure
  crackhash-worker-3:
    env_file:
      - .env
    build: ./worker/
    networks:
      - crackhash
    restart: on-failure
  crackhash-worker-4:
    env_file:
      - .env
    build: ./worker/
    networks:
      - crackhash
    restart: on-failure

networks:
  crackhash:
    driver: bridge

