workers:
  base_url: ${WORKER_BASE_URL}
  count: ${WORKERS_COUNT}
  timeout: ${TIMEOUT}

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}
    virtual-host: ${RABBIT_VHOST}
